version: '3'
services:
  api:
    image: fowner:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    command: [ "fowner", "serve" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - "./data:/opt/fowner"
      - ${SSH_AUTH_SOCK}:/ssh-agent
